### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by airon90**
+Italian translation of strings.xml

### CODE REVIEW

**Comment by airon90** [comment]
@jaredforrest can you merge my edits please? :)

**Comment by jaredforrest** [comment]
Sorry I've been away. Can you add a file 10.txt and then I will merge and update app.

**Comment by airon90** [comment]
Ok don't worry :) I will do it tomorrow (it's 00:20 now)

**Comment by airon90** [comment]
Done :)

**Pull request merged**
